services:
  - type: web
    name: revine-ai
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
